version: '3.8'

services:
  example-curse-fastapi:
    container_name: example-curse-fastapi
    env_file:
      - ./.env
    build: .
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8031:5000
    volumes:
      - .:/app/example-curse-fastapi
